# Generated by Django 5.2.11 on 2026-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_rename_servers_dis_snapsho_7143be_idx_servers_dis_snapsho_5641ff_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diskmetric",
            name="available_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diskmetric",
            name="filesystem",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="cpu_cores",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="ram_available_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="ram_available_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="ram_buffers_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="ram_cached_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="ram_free_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="ram_free_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="ram_shared_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="swap_cached_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="swap_free_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="swap_free_percent",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
