# Generated by Django 5.2.11 on 2026-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0003_diskmetric_available_bytes_diskmetric_filesystem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diskmetric",
            name="filesystem",
            field=models.CharField(blank=True, db_default="", default="", max_length=255),
        ),
    ]
