# Generated by Django 5.2.11 on 2026-02-23 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servers", "0002_rename_servers_dis_snapsho_7143be_idx_servers_dis_snapsho_5641ff_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(choices=[("warning", "Warning"), ("critical", "Critical")], max_length=10),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("cpu_load_1", "CPU Load (1 min)"),
                            ("cpu_load_5", "CPU Load (5 min)"),
                            ("cpu_load_15", "CPU Load (15 min)"),
                            ("ram_percent", "RAM Usage %"),
                            ("ram_used", "RAM Used (bytes)"),
                            ("swap_percent", "Swap Usage %"),
                            ("disk_percent", "Disk Usage %"),
                            ("disk_used", "Disk Used (bytes)"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metric_param", models.CharField(blank=True, default="", max_length=255)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("gt", "Greater than"),
                            ("lt", "Less than"),
                            ("eq", "Equals"),
                            ("gte", "Greater than or equals"),
                            ("lte", "Less than or equals"),
                            ("in_range", "Within range"),
                            ("out_of_range", "Outside range"),
                        ],
                        max_length=20,
                    ),
                ),
                ("threshold_value", models.FloatField()),
                ("threshold_value_2", models.FloatField(blank=True, null=True)),
                ("reminder_interval_minutes", models.PositiveIntegerField(default=0)),
                ("notify_on_dismissal", models.BooleanField(default=False)),
                ("dismissal_threshold_minutes", models.PositiveIntegerField(default=5)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "current_state",
                    models.CharField(
                        choices=[("normal", "Normal"), ("triggered", "Triggered")], default="normal", max_length=10
                    ),
                ),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("condition_cleared_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="alert_rules", to="servers.server"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[("triggered", "Triggered"), ("reminded", "Reminded"), ("dismissed", "Dismissed")],
                        max_length=10,
                    ),
                ),
                ("metric_value", models.FloatField()),
                ("threshold_value", models.FloatField()),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="alert_events", to="servers.server"
                    ),
                ),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="alerts.alertrule"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(fields=["server", "enabled"], name="alerts_aler_server__462f9e_idx"),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["server", "-created_at"], name="alerts_aler_server__7d91d1_idx"),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["alert_rule", "-created_at"], name="alerts_aler_alert_r_da02fd_idx"),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["event_type", "-created_at"], name="alerts_aler_event_t_261824_idx"),
        ),
    ]
