# Generated by Django 5.2.11 on 2026-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("cpu_load_1", "CPU Load (1 min)"),
                    ("cpu_load_5", "CPU Load (5 min)"),
                    ("cpu_load_15", "CPU Load (15 min)"),
                    ("ram_percent", "RAM Usage %"),
                    ("ram_used", "RAM Used (bytes)"),
                    ("ram_free", "RAM Free (bytes)"),
                    ("ram_available", "RAM Available (bytes)"),
                    ("ram_cached", "RAM Cached (bytes)"),
                    ("ram_free_pct", "RAM Free %"),
                    ("ram_available_pct", "RAM Available %"),
                    ("swap_percent", "Swap Usage %"),
                    ("swap_used", "Swap Used (bytes)"),
                    ("swap_free", "Swap Free (bytes)"),
                    ("swap_free_pct", "Swap Free %"),
                    ("disk_percent", "Disk Usage %"),
                    ("disk_used", "Disk Used (bytes)"),
                    ("disk_free", "Disk Free (bytes)"),
                    ("disk_free_pct", "Disk Free %"),
                    ("custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
