# Generated by Django 5.2.11 on 2026-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_alter_alertrule_metric_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertrule",
            name="dismissal_threshold_minutes",
        ),
        migrations.AddField(
            model_name="alertrule",
            name="dismissal_threshold_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="dismissal_threshold_value_2",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
