# Generated by Django 5.2.11 on 2026-02-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_remove_alertrule_dismissal_threshold_minutes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultAlertTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(choices=[("warning", "Warning"), ("critical", "Critical")], max_length=10),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("cpu_load_1", "CPU Load (1 min)"),
                            ("cpu_load_5", "CPU Load (5 min)"),
                            ("cpu_load_15", "CPU Load (15 min)"),
                            ("ram_percent", "RAM Usage %"),
                            ("ram_used", "RAM Used (bytes)"),
                            ("ram_free", "RAM Free (bytes)"),
                            ("ram_available", "RAM Available (bytes)"),
                            ("ram_cached", "RAM Cached (bytes)"),
                            ("ram_free_pct", "RAM Free %"),
                            ("ram_available_pct", "RAM Available %"),
                            ("swap_percent", "Swap Usage %"),
                            ("swap_used", "Swap Used (bytes)"),
                            ("swap_free", "Swap Free (bytes)"),
                            ("swap_free_pct", "Swap Free %"),
                            ("disk_percent", "Disk Usage %"),
                            ("disk_used", "Disk Used (bytes)"),
                            ("disk_free", "Disk Free (bytes)"),
                            ("disk_free_pct", "Disk Free %"),
                            ("uptime", "Uptime (seconds)"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metric_param", models.CharField(blank=True, default="", max_length=255)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("gt", "Greater than"),
                            ("lt", "Less than"),
                            ("eq", "Equals"),
                            ("gte", "Greater than or equals"),
                            ("lte", "Less than or equals"),
                            ("in_range", "Within range"),
                            ("out_of_range", "Outside range"),
                        ],
                        max_length=20,
                    ),
                ),
                ("threshold_value", models.FloatField()),
                ("threshold_value_2", models.FloatField(blank=True, null=True)),
                ("reminder_interval_minutes", models.PositiveIntegerField(default=0)),
                ("notify_on_dismissal", models.BooleanField(default=False)),
                ("dismissal_threshold_value", models.FloatField(blank=True, null=True)),
                ("dismissal_threshold_value_2", models.FloatField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="alertrule",
            name="cloned_from_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cloned_rules",
                to="alerts.defaultalerttemplate",
            ),
        ),
    ]
