# Generated by Django 5.2.11 on 2026-02-26 15:04

import django.db.models.deletion
from django.db import migrations, models


def migrate_default_templates_to_alert_rules(apps, schema_editor):  # noqa: ARG001
    DefaultAlertTemplate = apps.get_model("alerts", "DefaultAlertTemplate")
    AlertRule = apps.get_model("alerts", "AlertRule")

    for template in DefaultAlertTemplate.objects.all():
        AlertRule.objects.create(
            server=None,
            is_default_template=True,
            name=template.name,
            severity=template.severity,
            metric_type=template.metric_type,
            metric_param=template.metric_param,
            condition=template.condition,
            threshold_value=template.threshold_value,
            threshold_value_2=template.threshold_value_2,
            reminder_interval_minutes=template.reminder_interval_minutes,
            notify_on_dismissal=template.notify_on_dismissal,
            dismissal_threshold_value=template.dismissal_threshold_value,
            dismissal_threshold_value_2=template.dismissal_threshold_value_2,
            enabled=template.enabled,
            current_state="normal",
            triggered_at=None,
            last_reminder_at=None,
            condition_cleared_at=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0005_defaultalerttemplate_alertrule_cloned_from_template"),
        ("servers", "0004_alter_diskmetric_filesystem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertrule",
            name="cloned_from_template",
        ),
        migrations.AddField(
            model_name="alertrule",
            name="is_default_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                to="servers.server",
            ),
        ),
        migrations.RunPython(
            code=migrate_default_templates_to_alert_rules,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="DefaultAlertTemplate",
        ),
    ]
