# Generated by Django 5.2.11 on 2026-02-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0006_remove_alertrule_cloned_from_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertevent",
            name="notification_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
