# Generated by Django 5.2.11 on 2026-02-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="diskmetric",
            new_name="servers_dis_snapsho_5641ff_idx",
            old_name="servers_dis_snapsho_7143be_idx",
        ),
        migrations.RenameIndex(
            model_name="metricsnapshot",
            new_name="servers_met_server__5f3f5f_idx",
            old_name="servers_met_server__e9b54d_idx",
        ),
    ]
